# Generated by Django 5.2.5 on 2025-08-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AIRPORT_SERVICE', 'Airport Service'), ('CAR_RENTAL', 'Car Rental')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded')], db_index=True, default='PAID', max_length=16)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'created_at'], name='orders_orde_categor_1cab9a_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx')],
            },
        ),
    ]
