# Generated by Django 5.2.5 on 2025-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_airportservice_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airportservice',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='airportservice',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
